// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8KwVY711z28UnCzpadZF6VIcsCStv-Iw',
    appId: '1:861416421243:web:97c32c0000e7d4fc1e2fde',
    messagingSenderId: '861416421243',
    projectId: 'userprofile-7b170',
    authDomain: 'userprofile-7b170.firebaseapp.com',
    storageBucket: 'userprofile-7b170.firebasestorage.app',
    measurementId: 'G-91NQC0ZB4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEQlgnwqlasjS6R1gE6xDnz76t1WoFWJE',
    appId: '1:861416421243:android:7819fcabc16c8d2d1e2fde',
    messagingSenderId: '861416421243',
    projectId: 'userprofile-7b170',
    storageBucket: 'userprofile-7b170.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHCjNSXWMVuW6eqIb2NW0In2kV2RpJcBs',
    appId: '1:861416421243:ios:001ce103a9ac1e6e1e2fde',
    messagingSenderId: '861416421243',
    projectId: 'userprofile-7b170',
    storageBucket: 'userprofile-7b170.firebasestorage.app',
    iosBundleId: 'com.example.userLoginProfile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHCjNSXWMVuW6eqIb2NW0In2kV2RpJcBs',
    appId: '1:861416421243:ios:001ce103a9ac1e6e1e2fde',
    messagingSenderId: '861416421243',
    projectId: 'userprofile-7b170',
    storageBucket: 'userprofile-7b170.firebasestorage.app',
    iosBundleId: 'com.example.userLoginProfile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8KwVY711z28UnCzpadZF6VIcsCStv-Iw',
    appId: '1:861416421243:web:817d24d9859fd8261e2fde',
    messagingSenderId: '861416421243',
    projectId: 'userprofile-7b170',
    authDomain: 'userprofile-7b170.firebaseapp.com',
    storageBucket: 'userprofile-7b170.firebasestorage.app',
    measurementId: 'G-P9V8R68FT5',
  );
}
