import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart'; // ADDED: Required to listen to login state
import 'package:user_login_profile/User_Login/userloginpage.dart';
import 'package:user_login_profile/userprofil.dart'; // ADDED: Required to route to the profile screen
import 'firebase_options.dart'; // This is the file generated by the CLI in Step 1

void main() async {
  // 1. Ensure the Flutter framework bindings are ready
  WidgetsFlutterBinding.ensureInitialized();
  
  // 2. Asynchronously initialize Firebase for the active platform
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      // CHANGED: Instead of hardcoding UserLogin(), we point to our Auth Gate checkpoint
      home: AuthGate(), 
    );
  }
}

// ADDED: This widget controls whether to show the Login Screen or the Profile Screen on startup
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      // Firebase automatically checks your device's local memory for a saved login session here
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // 1. While waiting for Firebase to read the saved data, show a loading spinner
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }

        // 2. If a valid user session is found in memory, boot straight to the profile page
        if (snapshot.hasData && snapshot.data != null) {
          return const UserProfileScreen();
        }
        
        // 3. If no login session is found, show the login interface
        return const UserLogin();
      },
    );
  }
}